spring:
    application:
        name: spring-sec-6-demo

    datasource:
        url: jdbc:postgresql://localhost:5432/springsecurity
        username: postgres
        password : Bingo
    jpa:
        hibernate:
            ddl-auto: create
            show_sql: true
            format-sql : true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        org.springframework.security : TRACE

